// <auto-generated />
using System;
using HotelService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelService.Data.Migrations.Catalog
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelService.Entities.Hotel", b =>
                {
                    b.Property<Guid>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BaseRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.HasKey("HotelId");

                    b.HasIndex("Destination")
                        .HasDatabaseName("IX_Hotels_Destination");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000001"),
                            BaseRating = 9.2m,
                            Destination = "Istanbul",
                            IsActive = true,
                            Latitude = 41.0423m,
                            Longitude = 29.0082m,
                            Name = "Swissôtel The Bosphorus Istanbul",
                            TotalReviews = 1284
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000002"),
                            BaseRating = 8.8m,
                            Destination = "Istanbul",
                            IsActive = true,
                            Latitude = 41.0603m,
                            Longitude = 28.9844m,
                            Name = "Hilton Istanbul Bomonti",
                            TotalReviews = 876
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000003"),
                            BaseRating = 9.0m,
                            Destination = "Izmir",
                            IsActive = true,
                            Latitude = 38.4192m,
                            Longitude = 27.1287m,
                            Name = "Swissôtel Büyük Efes Izmir",
                            TotalReviews = 643
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000004"),
                            BaseRating = 9.6m,
                            Destination = "Bodrum",
                            IsActive = true,
                            Latitude = 37.0344m,
                            Longitude = 27.4305m,
                            Name = "Hyde Bodrum - Yetişkin Oteli",
                            TotalReviews = 163
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000005"),
                            BaseRating = 9.4m,
                            Destination = "Bodrum",
                            IsActive = true,
                            Latitude = 37.1041m,
                            Longitude = 27.2866m,
                            Name = "MGallery The Bodrum Hotel Yalıkavak",
                            TotalReviews = 302
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000006"),
                            BaseRating = 9.1m,
                            Destination = "Antalya",
                            IsActive = true,
                            Latitude = 36.8531m,
                            Longitude = 30.7512m,
                            Name = "Regnum Carya Golf & Spa Resort",
                            TotalReviews = 529
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000007"),
                            BaseRating = 9.3m,
                            Destination = "Antalya",
                            IsActive = true,
                            Latitude = 36.8642m,
                            Longitude = 31.0667m,
                            Name = "Rixos Premium Belek",
                            TotalReviews = 1102
                        });
                });

            modelBuilder.Entity("HotelService.Entities.InventoryBlock", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("InventoryId");

                    b.HasIndex("RoomTypeId")
                        .HasDatabaseName("IX_InventoryBlocks_RoomTypeId");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_InventoryBlocks_StartDate_EndDate");

                    b.ToTable("InventoryBlocks");

                    b.HasData(
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000001"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000002"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000003"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000004"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000005"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000006"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000007"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000008"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000009"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000010"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000011"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000012"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000013"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000014"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000015"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000016"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000006"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000017"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000006"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000018"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000006"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000019"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000007"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000020"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000007"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000021"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000007"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000022"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000008"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000023"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000008"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000024"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000008"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000025"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000009"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000026"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000009"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000027"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000009"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000028"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000010"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000029"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000010"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000030"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000010"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000031"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000011"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000032"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000011"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000033"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000011"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000034"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000012"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000035"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000012"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000036"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000012"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000037"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000013"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000038"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000013"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000039"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000013"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000040"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000014"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000041"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000014"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000042"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000014"),
                            RowVersion = new byte[0],
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        });
                });

            modelBuilder.Entity("HotelService.Entities.RoomType", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomTypeId");

                    b.HasIndex("HotelId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            BasePricePerNight = 4200m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000001"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            BasePricePerNight = 7800m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000001"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            BasePricePerNight = 3500m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000002"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            BasePricePerNight = 6200m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000002"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            BasePricePerNight = 3100m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000003"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000006"),
                            BasePricePerNight = 5800m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000003"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000007"),
                            BasePricePerNight = 10948m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000004"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000008"),
                            BasePricePerNight = 18500m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000004"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000009"),
                            BasePricePerNight = 9458m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000005"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000010"),
                            BasePricePerNight = 15900m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000005"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000011"),
                            BasePricePerNight = 6500m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000006"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000012"),
                            BasePricePerNight = 11200m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000006"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000013"),
                            BasePricePerNight = 8200m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000007"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000014"),
                            BasePricePerNight = 14600m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000007"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        });
                });

            modelBuilder.Entity("HotelService.Entities.InventoryBlock", b =>
                {
                    b.HasOne("HotelService.Entities.RoomType", "RoomType")
                        .WithMany("InventoryBlocks")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelService.Entities.RoomType", b =>
                {
                    b.HasOne("HotelService.Entities.Hotel", "Hotel")
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelService.Entities.Hotel", b =>
                {
                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("HotelService.Entities.RoomType", b =>
                {
                    b.Navigation("InventoryBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
