// <auto-generated />
using System;
using HotelService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelService.Data.Migrations.Catalog
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelService.Entities.Hotel", b =>
                {
                    b.Property<Guid>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BaseRating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer");

                    b.HasKey("HotelId");

                    b.HasIndex("Destination")
                        .HasDatabaseName("IX_Hotels_Destination");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000001"),
                            BaseRating = 9.2m,
                            Description = "Perched above the Bosphorus Strait with panoramic views of two continents, Swissôtel The Bosphorus combines Swiss precision with Istanbul's timeless elegance. The hotel features award-winning spa facilities, multiple fine-dining restaurants, and a rooftop infinity pool overlooking the historic skyline.",
                            Destination = "Istanbul",
                            ImageUrl = "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80",
                            IsActive = true,
                            Latitude = 41.04350m,
                            Longitude = 29.00810m,
                            Name = "Swissôtel The Bosphorus Istanbul",
                            TotalReviews = 1284
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000002"),
                            BaseRating = 8.8m,
                            Description = "Located in Istanbul's vibrant Bomonti district, this modern high-rise hotel offers sweeping city views from its Sky Bar and rooftop pool. With spacious contemporary rooms, a fully equipped fitness center, and direct access to local nightlife, it's the ideal urban retreat.",
                            Destination = "Istanbul",
                            ImageUrl = "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
                            IsActive = true,
                            Latitude = 41.06110m,
                            Longitude = 28.98360m,
                            Name = "Hilton Istanbul Bomonti",
                            TotalReviews = 876
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000003"),
                            BaseRating = 9.0m,
                            Description = "Izmir's most iconic luxury hotel, the Büyük Efes sits in the heart of the city overlooking the Gulf of İzmir. The landmark property features beautifully appointed rooms, a grand swimming pool, and is steps away from the lively Kordon waterfront promenade.",
                            Destination = "Izmir",
                            ImageUrl = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
                            IsActive = true,
                            Latitude = 38.41920m,
                            Longitude = 27.12610m,
                            Name = "Swissôtel Büyük Efes Izmir",
                            TotalReviews = 643
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000004"),
                            BaseRating = 9.6m,
                            Description = "An exclusive adults-only retreat set on the crystal-clear waters of the Bodrum Peninsula. Hyde Bodrum offers private beach access, sunset cocktail terraces, and a serene infinity pool, creating a sophisticated escape where style meets the Aegean Sea.",
                            Destination = "Bodrum",
                            ImageUrl = "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
                            IsActive = true,
                            Latitude = 37.03380m,
                            Longitude = 27.43060m,
                            Name = "Hyde Bodrum - Yetişkin Oteli",
                            TotalReviews = 163
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000005"),
                            BaseRating = 9.4m,
                            Description = "Nestled in the exclusive marina of Yalıkavak, this boutique MGallery property captures the charm of traditional Bodrum architecture with world-class amenities. Enjoy private sea access, a tranquil spa, and gourmet dining with views of luxury yachts and the Aegean.",
                            Destination = "Bodrum",
                            ImageUrl = "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80",
                            IsActive = true,
                            Latitude = 37.10430m,
                            Longitude = 27.28170m,
                            Name = "MGallery The Bodrum Hotel Yalıkavak",
                            TotalReviews = 302
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000006"),
                            BaseRating = 9.1m,
                            Description = "A grand beachfront resort on the Belek Riviera, Regnum Carya combines championship golf courses, a sprawling water park, and an award-winning spa. With multiple pools, private beach, and all-inclusive dining options, this is Antalya's premier family and leisure destination.",
                            Destination = "Antalya",
                            ImageUrl = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
                            IsActive = true,
                            Latitude = 36.85740m,
                            Longitude = 30.75300m,
                            Name = "Regnum Carya Golf & Spa Resort",
                            TotalReviews = 529
                        },
                        new
                        {
                            HotelId = new Guid("11111111-0000-0000-0000-000000000007"),
                            BaseRating = 9.3m,
                            Description = "Rixos Premium Belek sets the standard for Turkish Riviera luxury with its extensive Ultra All-Inclusive concept. Set among lush pine forests steps from the Mediterranean, guests enjoy multiple pools, a private beach, a top-tier spa, and over 20 restaurants and bars.",
                            Destination = "Antalya",
                            ImageUrl = "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
                            IsActive = true,
                            Latitude = 36.86980m,
                            Longitude = 31.06490m,
                            Name = "Rixos Premium Belek",
                            TotalReviews = 1102
                        });
                });

            modelBuilder.Entity("HotelService.Entities.InventoryBlock", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("InventoryId");

                    b.HasIndex("RoomTypeId")
                        .HasDatabaseName("IX_InventoryBlocks_RoomTypeId");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_InventoryBlocks_StartDate_EndDate");

                    b.ToTable("InventoryBlocks");

                    b.HasData(
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000001"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000002"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000003"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000004"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000005"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000006"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000007"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000008"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000009"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000010"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000011"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000012"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000013"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000014"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000015"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000016"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000006"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000017"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000006"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000018"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000006"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000019"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000007"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000020"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000007"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000021"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000007"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000022"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000008"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000023"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000008"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000024"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000008"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000025"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000009"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000026"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000009"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000027"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000009"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000028"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000010"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000029"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000010"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000030"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000010"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000031"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000011"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000032"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000011"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000033"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000011"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000034"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000012"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000035"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000012"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000036"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000012"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000037"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000013"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000038"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000013"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000039"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000013"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000040"),
                            AvailableCount = 10,
                            EndDate = new DateOnly(2026, 6, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000014"),
                            StartDate = new DateOnly(2026, 5, 10),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000041"),
                            AvailableCount = 1,
                            EndDate = new DateOnly(2026, 7, 9),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000014"),
                            StartDate = new DateOnly(2026, 6, 9),
                            TotalCount = 10
                        },
                        new
                        {
                            InventoryId = new Guid("33333333-0000-0000-0000-000000000042"),
                            AvailableCount = 8,
                            EndDate = new DateOnly(2026, 8, 8),
                            IsAvailable = true,
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000014"),
                            StartDate = new DateOnly(2026, 7, 9),
                            TotalCount = 10
                        });
                });

            modelBuilder.Entity("HotelService.Entities.RoomType", b =>
                {
                    b.Property<Guid>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoomTypeId");

                    b.HasIndex("HotelId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000001"),
                            BasePricePerNight = 4200m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000001"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000002"),
                            BasePricePerNight = 7800m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000001"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000003"),
                            BasePricePerNight = 3500m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000002"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000004"),
                            BasePricePerNight = 6200m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000002"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000005"),
                            BasePricePerNight = 3100m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000003"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000006"),
                            BasePricePerNight = 5800m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000003"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000007"),
                            BasePricePerNight = 10948m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000004"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000008"),
                            BasePricePerNight = 18500m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000004"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000009"),
                            BasePricePerNight = 9458m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000005"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000010"),
                            BasePricePerNight = 15900m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000005"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000011"),
                            BasePricePerNight = 6500m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000006"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000012"),
                            BasePricePerNight = 11200m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000006"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000013"),
                            BasePricePerNight = 8200m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000007"),
                            MaxGuests = 2,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeId = new Guid("22222222-0000-0000-0000-000000000014"),
                            BasePricePerNight = 14600m,
                            HotelId = new Guid("11111111-0000-0000-0000-000000000007"),
                            MaxGuests = 4,
                            TypeName = "Family"
                        });
                });

            modelBuilder.Entity("HotelService.Entities.InventoryBlock", b =>
                {
                    b.HasOne("HotelService.Entities.RoomType", "RoomType")
                        .WithMany("InventoryBlocks")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("HotelService.Entities.RoomType", b =>
                {
                    b.HasOne("HotelService.Entities.Hotel", "Hotel")
                        .WithMany("RoomTypes")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelService.Entities.Hotel", b =>
                {
                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("HotelService.Entities.RoomType", b =>
                {
                    b.Navigation("InventoryBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
